### ISSUE TITLE
Bartender 2

### ISSUE THREAD

**Issue by svtzr** [sketchpacks/feedback#11]
Love the app. Just wanted to point out for those of us who use a Mac Menu Bar organiser like Bartender 2, the Sketchpacks window doesn't move below it and covers the search bar. (Photo attached)

Bartender has a fix for these kinds of apps, however, it doesn't work with Sketchpacks. Would love to see this fixed in the next release.

<img width="785" alt="screen shot 2017-03-25 at 11 56 24 am" src="https://cloud.githubusercontent.com/assets/14270631/24318507/4cbc9d44-1152-11e7-9437-2aa541fd66b3.png">

**Comment by adamkirkwood** [comment]
@svtzr Thanks for the feedback. We'll be addressing this issue in the v0.5.2 update

**Comment by adamkirkwood** [comment]
![screen shot 2017-03-29 at 7 51 09 am](https://cloud.githubusercontent.com/assets/52746/24460912/81e98cc0-1454-11e7-909f-c8ccce38ad89.png)
