### ISSUE TITLE
Display number of installations of the plugin

### ISSUE THREAD

**Issue by solo-s** [sketchpacks/feedback#15]
Beside the #7 stars, is it possible to show count of plugin installations, like in Atom. You can count it directly in your app after success installation.

<img width="678" alt="atom packages" src="https://cloud.githubusercontent.com/assets/5980712/24606229/debac8a0-1874-11e7-9013-8e3f53a1de04.png">

**Comment by adamkirkwood** [comment]
@e1ectron This has been added in `0.5.7`

Thanks for the great feedback!
