### ISSUE TITLE
Allow Command + A to be used when highlighting the search all plugins box

### ISSUE THREAD

**Issue by 3raxton** [sketchpacks/feedback#16]
When typing I prefer to select all text with Command + A rather than pressing backspace or Shift + Alt + Arrow Keys. This would make it much more convenient when searching for plugins.

**Comment by adamkirkwood** [comment]
@3raxton `v0.5.6` addresses this issue.

As always, thanks for the great feedback!

**Comment by 3raxton** [comment]
Awesome! Can't wait to see what comes next!
