### ISSUE TITLE
The Search no working correctly

### ISSUE THREAD

**Issue by josealvarezn** [sketchpacks/feedback#2]
When I search any plugin, the search not showme the correct results or notting. :(
![screen shot 2017-03-14 at 4 38 18 pm](https://cloud.githubusercontent.com/assets/16816916/23921340/b8fe7f58-08d4-11e7-9c78-13e2fcd5792e.png)

**Comment by willdavis** [comment]
Hi @josealvarezn, thanks for the feedback!
I'm seeing the same thing when I search for `symbol organizer`.  It looks like our search feature is having problems with multiple words.  This should be working so I'll escalate it as a bug.

When I search for single words like `symbol` or `organizer` I'm able to see results.  Can you please confirm if you're able to do the same?

**Comment by josealvarezn** [comment]
Yes, the problem is with multiple words.

**Comment by simpsondesign** [comment]
I'm also not seeing results for single words, like "sketchrunner", which would resolve to: https://github.com/sketchrunner/sketchrunner.github.io

So far, this seems to be the only one that didn't work for me. Looking forward to trying this out!

**Comment by rodnem** [comment]
A-Z is selected (in case of...)
I've type Path, Rectangle, Count
NO RESULTS

I think you have to expand your search to description, to readme.md

**Comment by adamkirkwood** [comment]
Search has been improved a few versions ago. Will be closing this out.
