### ISSUE TITLE
Site SEO

### ISSUE THREAD

**Issue by kylamedina** [sketchpacks/feedback#20]
I really love this app but it took me several Google attempts to find it. Searches like 'Sketch Pack', 'Sketchpack', 'Sketch Pack Plugins' didn't find anything.

Just an observation for your consideration.

**Comment by adamkirkwood** [comment]
@kylamedina Thanks for the feedback! We completely agree. There's still some work to be done before our push for SEO, but it will be a huge focus after `0.6.0` is released.

**Comment by adamkirkwood** [comment]
@kylamedina We've finally released our new web registry with much improvements to our SEO efforts.

Thanks for the feedback and support!
