### ISSUE TITLE
Allow to change default setting for version locking

### ISSUE THREAD

**Issue by fbasara-loft48** [sketchpacks/feedback#24]
Please add the functionality to allow users to change the default settings of a newly installed plugin to be locked or unlocked. I didn't realise my plugins were locked from updating because the icon for locking and unlocking is looking pretty similar. Maybe changing the icon would be benefitial.

**Comment by adamkirkwood** [comment]
@fbasara-loft48 With Sketchpacks 0.6.0, you now have the ability to define a default locking and updating strategy from the `Preferences` menu.

![screen shot 2017-09-09 at 5 41 49 pm](https://user-images.githubusercontent.com/52746/30245173-2e46621a-9586-11e7-9aa6-755968060420.png)

**Comment by fbasara-loft48** [comment]
Thanks a lot!
