### ISSUE TITLE
The plugin seems doesn't recognise installed plugin in Sketch 43.2

### ISSUE THREAD

**Issue by badyqb** [sketchpacks/feedback#26]
When installed, there is no plugin installed while actually I already install many plugins.
[Here's how it looks like](http://d.pr/i/pImOb), vs [plugin manager on sketch ](http://d.pr/i/akv4e)

**Comment by adamkirkwood** [comment]
@badyqb This has been fixed in `0.5.7`

Thanks for the feedback!
