### ISSUE TITLE
add githab links to plugins

### ISSUE THREAD

**Issue by illustree** [sketchpacks/feedback#3]
I very often try to improve plugins with my feedbacks and suggestions ... writing those down on github ... the way I did it before I started using Sketchpacks (which is btw something really awesome! thanks for that tool) ... I went to the Sketch Toolbox and searched the plugin, then clicked on the github link and created new issues  ... that is until now missing, please can you add?

**Comment by adamkirkwood** [comment]
@illustree That's great! We appreciate your efforts.

We'll work on making bug reporting more easily accessible from within the app.

Thanks for the feedback!

**Comment by adamkirkwood** [comment]
@illustree Github pages for plugins are accessible via Sketchpacks.com.

Thanks for the feedback!
