### ISSUE TITLE
[Question] [API] How is score calculated?

### ISSUE THREAD

**Issue by mludowise** [sketchpacks/feedback#35]
The Sketchpacks API has a `score` field. The description of this field is:
> Sketchpacks popularity score

It's not entirely clear to me what a "popularity score" is. Could someone please explain what this means?

**Comment by willdavis** [comment]
The popularity score is weighted based on the plugins stargazer/watcher count as well as the repositories age.

We plan to update this score in the future to make better use of the aggregated download metrics.
