### ISSUE TITLE
0.6 has meant broken interface

### ISSUE THREAD

**Issue by mijlee** [sketchpacks/feedback#39]
Updated to 0.6 today and now I no longer see any of the app UI and cannot use it or even quit. Have tried a full restart, still nothing.

https://www.dropbox.com/s/c589mv7jzrevbgr/Screenshot%202017-09-07%2015.49.31.png?dl=0

**Comment by adamkirkwood** [comment]
We've rolled out a fix for this issue in v0.6.1 which is [available for download now](https://bit.ly/GetSketchpacks).
