### ISSUE TITLE
How does this compare to Sketch Toolbox?

### ISSUE THREAD

**Issue by ghost** [sketchpacks/feedback#5]

**Comment by adamkirkwood** [comment]
@iampox In terms of feature parity with Sketch Toolbox, its the same plus some.

Sketchpacks detects new versions of plugins you've installed, and auto-updates them for you.

However, if you didn't want certain plugins auto-updated, we give you the option to lock the plugin at its current version.

We have quite a bit mapped out on the roadmap, but this is just the beginning.

You can read more about the app on our [blog](https://medium.com/building-sketchpacks/introducing-sketchpacks-for-macos-8f4df3313b95).

**Comment by ghost** [comment]
Ok thanks for the quick answer!
Does Sketchpacks propose as many plugins as Sketch Toolbox?

**Comment by adamkirkwood** [comment]
@iampox We index all the same plugins as Sketch Toolbox. However, we will be removing dead plugins as well as plugins without a `manifest.json` file soon to help keep the registry clean and only with usable plugins.
