### ISSUE TITLE
Option to Open at Login

### ISSUE THREAD

**Issue by josealvarezn** [sketchpacks/feedback#6]
I love the latest update with the option to import from Sketch Toolbox. 
Please, add option to Open Sketchpacks at Login when macOS boot.

Thanks! 👍

**Comment by adamkirkwood** [comment]
@josealvarezn Thanks for the feedback!

We have Auto Launch on the roadmap. Will definitely let you know when it will be released.

**Comment by josealvarezn** [comment]
Yey, thanks! 😊

**Comment by joshuakaufman** [comment]
+1

**Comment by adamkirkwood** [comment]
@josealvarezn @josealvarezn `Launch on startup` is now available in v0.5.3.
