### ISSUE TITLE
Display number of stars of the plugin repository

### ISSUE THREAD

**Issue by drasnop** [sketchpacks/feedback#7]
I love the look and functionality of Sketchpacks, but I miss seeing the number of stars the plugin's Github repository has. It's a strong indicator of how popular a plugin is. It would be great to show it next to the version number (I wouldn't mind the window to be a bit wider to accommodate it, or the install button to be a bit more narrow).

**Comment by adamkirkwood** [comment]
@drasnop Hey Antoine,

Thanks for the feedback! We will definitely surfacing more metrics such as Github Star count. We completely agree that it is a great indication of adoption.

We'll let you know once we push out that update.

**Comment by adamkirkwood** [comment]
@drasnop We've added download metrics in place of Github Star count for now as old plugins that are no longer working have a large volume of the Github Star counts.

So for now, this won't be fixed.

Thanks for the feedback!

**Comment by drasnop** [comment]
Makes sense!
