### ISSUE TITLE
Multiple machine plugin sync

### ISSUE THREAD

**Issue by yapjonathan** [sketchpacks/feedback#8]
Is this in the pipeline for folks who work on multiple machines?

Like exposing a simple .json list of plugins that you can put in dropbox/google drive/box/onedrive etc… and have sketch pack look for it?

Sublime text does a great job at this, and would love to see this available for multi-machine folks 😀

**Comment by adamkirkwood** [comment]
@yapjonathan Hey Jonathan! Thanks for the feedback. I believe this is a good route for us to explore in hopefully the near future. We'll definitely ping you when we have something you can try out.

**Comment by adamkirkwood** [comment]
@yapjonathan Hey Jonathan,

We're getting closer to having something usable. So far this is the schema we landed on for such a thing.

```
{
  "name": "Adam Kirkwood's Library",
  "schema_version": "0.1.0",
  "locked": false,
  "plugins": {
    "utom/sketch-measure": {
      "name": "sketch-measure",
      "owner": "utom",
      "version": "2.4.1",
      "version_range": [
        "2.4.1"
      ],
      "compatible_version": "0.0.0",
      "compatible_version_range": [
        "0.0.0"
      ]
    },
    "AnimaApp/auto-layout": {
      "name": "auto-layout",
      "owner": "AnimaApp",
      "version": "0.2.3",
      "version_range": [
        "0.2.3"
      ],
      "compatible_version": "41.0.0",
      "compatible_version_range": [
        "41.0.0"
      ]
    },
    ...
  }
}
```

**Comment by yapjonathan** [comment]
Super awesome, can't wait to try it out!

**Comment by adamkirkwood** [comment]
@yapjonathan Syncing Sketch plugins across machines and teams is now part of Sketchpacks 0.6.0

**Comment by sjamesmccarthy** [comment]
I am using v0.6.2
Where can I find some documentation on this?
